#!/bin/bash

../../../../code/get_PPI_intra_contact_onthefly_chains.py* ../6cmo.cif R A 5 > 6cmo_R_A_contacts.txt
../../../../code/get_PPI_intra_contact_onthefly_chains.py* ../6dde.cif R A 5 > 6dde_R_A_contacts.txt
../../../../code/get_PPI_intra_contact_onthefly_chains.py* ../6ddf.cif R A 5 > 6ddf_R_A_contacts.txt
../../../../code/get_PPI_intra_contact_onthefly_chains.py* ../6k42.cif R A 5 > 6k42_R_A_contacts.txt
../../../../code/get_PPI_intra_contact_onthefly_chains.py* ../6kpf.cif R A 5 > 6kpf_R_A_contacts.txt
../../../../code/get_PPI_intra_contact_onthefly_chains.py* ../6kpg.cif R A 5 > 6kpg_R_A_contacts.txt
../../../../code/get_PPI_intra_contact_onthefly_chains.py* ../6lfm.cif R A 5 > 6lfm_R_A_contacts.txt
../../../../code/get_PPI_intra_contact_onthefly_chains.py* ../6lfo.cif R A 5 > 6lfo_R_A_contacts.txt
../../../../code/get_PPI_intra_contact_onthefly_chains.py* ../6n4b.cif R A 5 > 6n4b_R_A_contacts.txt
../../../../code/get_PPI_intra_contact_onthefly_chains.py* ../6omm.cif R A 5 > 6omm_R_A_contacts.txt
../../../../code/get_PPI_intra_contact_onthefly_chains.py* ../6os9.cif R A 5 > 6os9_R_A_contacts.txt
../../../../code/get_PPI_intra_contact_onthefly_chains.py* ../6osa.cif R A 5 > 6osa_R_A_contacts.txt
../../../../code/get_PPI_intra_contact_onthefly_chains.py* ../6pt0.cif R A 5 > 6pt0_R_A_contacts.txt
../../../../code/get_PPI_intra_contact_onthefly_chains.py* ../6qno.cif R A 5 > 6qno_R_A_contacts.txt
../../../../code/get_PPI_intra_contact_onthefly_chains.py* ../6vms.cif R A 5 > 6vms_R_A_contacts.txt
../../../../code/get_PPI_intra_contact_onthefly_chains.py* ../7jvr.cif R A 5 > 7jvr_R_A_contacts.txt
../../../../code/get_PPI_intra_contact_onthefly_chains.py* ../7l0p.cif C A 5 > 7l0p_C_A_contacts.txt
../../../../code/get_PPI_intra_contact_onthefly_chains.py* ../7l0q.cif C A 5 > 7l0q_C_A_contacts.txt
../../../../code/get_PPI_intra_contact_onthefly_chains.py* ../7l0r.cif C A 5 > 7l0r_C_A_contacts.txt
../../../../code/get_PPI_intra_contact_onthefly_chains.py* ../7l0s.cif C A 5 > 7l0s_C_A_contacts.txt
../../../../code/get_PPI_intra_contact_onthefly_chains.py* ../mt1-gi1.cif.gz D A 5 > mt1-gi1_D_A_contacts.txt
../../../../code/get_PPI_intra_contact_onthefly_chains.py* ../6d9h.cif R A 5 > 6d9h_R_A_contacts.txt
../../../../code/get_PPI_intra_contact_onthefly_chains.py* ../6g79.cif S A 5 > 6g79_S_A_contacts.txt
../../../../code/get_PPI_intra_contact_onthefly_chains.py* ../6k41.cif R A 5 > 6k41_R_A_contacts.txt
../../../../code/get_PPI_intra_contact_onthefly_chains.py* ../6oik.cif R A 5 > 6oik_R_A_contacts.txt
../../../../code/get_PPI_intra_contact_onthefly_chains.py* ../6wwz.cif R A 5 > 6wwz_R_A_contacts.txt
../../../../code/get_PPI_intra_contact_onthefly_chains.py* ../6oy9.cif R A 5 > 6oy9_R_A_contacts.txt
../../../../code/get_PPI_intra_contact_onthefly_chains.py* ../6oya.cif R A 5 > 6oya_R_A_contacts.txt
../../../../code/get_PPI_intra_contact_onthefly_chains.py* ../3sn6.cif R A 5 > 3sn6_R_A_contacts.txt
../../../../code/get_PPI_intra_contact_onthefly_chains.py* ../6gdg.cif A D 5 > 6gdg_A_D_contacts.txt
../../../../code/get_PPI_intra_contact_onthefly_chains.py* ../6li3.cif R A 5 > 6li3_R_A_contacts.txt
../../../../code/get_PPI_intra_contact_onthefly_chains.py* ../6ni3.cif R A 5 > 6ni3_R_A_contacts.txt
../../../../code/get_PPI_intra_contact_onthefly_chains.py* ../7bz2.cif R A 5 > 7bz2_R_A_contacts.txt
../../../../code/get_PPI_intra_contact_onthefly_chains.py* ../7cfm.cif R A 5 > 7cfm_R_A_contacts.txt
../../../../code/get_PPI_intra_contact_onthefly_chains.py* ../7cfn.cif R A 5 > 7cfn_R_A_contacts.txt
../../../../code/get_PPI_intra_contact_onthefly_chains.py* ../7d7m.cif A D 5 > 7d7m_A_D_contacts.txt
../../../../code/get_PPI_intra_contact_onthefly_chains.py* ../7dhi.cif R A 5 > 7dhi_R_A_contacts.txt
../../../../code/get_PPI_intra_contact_onthefly_chains.py* ../7dhr.cif R A 5 > 7dhr_R_A_contacts.txt
../../../../code/get_PPI_intra_contact_onthefly_chains.py* ../7jjo.cif R A 5 > 7jjo_R_A_contacts.txt
../../../../code/get_PPI_intra_contact_onthefly_chains.py* ../7jv5.cif R A 5 > 7jv5_R_A_contacts.txt
../../../../code/get_PPI_intra_contact_onthefly_chains.py* ../7jvp.cif R A 5 > 7jvp_R_A_contacts.txt
../../../../code/get_PPI_intra_contact_onthefly_chains.py* ../7bw0.cif R A 5 > 7bw0_R_A_contacts.txt
../../../../code/get_PPI_intra_contact_onthefly_chains.py* ../7jvq.cif R A 5 > 7jvq_R_A_contacts.txt
